README.md
Add "how to contribute part" in readme.
=> [Doc]add contribute process description

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Add issue and PR template config.
none
=> [Config]add issue and pr template

.github/workflows/cmake.yml, CMakeLists.txt
=> Basic CI Support

README.md, docs/docs.en/HowToFixIssue.md
like title, for #7 
add a document file
=> add how to fix issue document

.github/workflows/clang-format.yml
Now the CI would test the format of the changed code.
Closed #10
=> Clang Format CI

demo_example/CMakeLists.txt, demo_example/asio_util.hpp, demo_example/async_echo_client.cpp, demo_example/http/coroutine_http/http_client.cpp, demo_example/smtp/smtp_client.cpp, demo_example/smtp/test_file.txt
Add a demo to Show how to send email with async_simple.
none
=> [Demo example]Show how to send email with async_simple

README.md
In previous document, we don't require developer to run test and format before committing, which is necessary.
=> Require to run test and format in README

async_simple/Executor.h, demo_example/asio_util.hpp
Make custom executor definition more easier.
Modify some pure virtual functions to non pure virtual functions, custom executor only need to override only one function, we have to override 4 functions before.
=> [Executor interface]mod interface

README.md, README_CN.md
=> add chinese readme

async_simple/uthread/internal/thread.cc
thread.cc is not formated in previous commit due to the suffix.
=> Format thread.cc

CMakeLists.txt, README.md, async_simple/coro/Collect.h, async_simple/coro/Task.h, async_simple/coro/test/LazyTest.cpp, async_simple/uthread/internal/thread.cc, async_simple/uthread/test/UthreadTest.cpp, async_simple/util/ThreadPool.h
=> add support for gcc

README.md, README_CN.md
Tell the developers the place they could track the performance.
=> Update documentation for performance moniotring

async_simple/coro/CoAwait.h, async_simple/coro/FutureAwaiter.h, async_simple/coro/Traits.h, async_simple/coro/test/FutureAwaiterTest.cpp
Close #37 
add FutureAwaiter.h and Test source
```c++
Promise<T> pr;
auto fut = pr.getFuture();
// invoke pr.setValue() in callback
auto val = co_await FutureAwaiter(std::move(fut));
```
=> [coro] Add FutureAwaiter

async_simple/Future.h, async_simple/coro/test/LazyTest.cpp, async_simple/executors/SimpleExecutor.h, async_simple/executors/SimpleIOExecutor.h, async_simple/executors/test/SimpleIOExecutorTest.cpp, async_simple/test/FutureTest.cpp, async_simple/uthread/test/UthreadTest.cpp, async_simple/util/ThreadPool.h
=> [Cross platform]remove usleep

.github/workflows/PerformanceCommit.yml, .github/workflows/PerformancePR.yml, benchmarks/CMakeLists.txt, benchmarks/Future.bench.cpp, benchmarks/Future.bench.h, benchmarks/Lazy.bench.cpp, benchmarks/Lazy.bench.h, benchmarks/Uthread.bench.cpp, benchmarks/Uthread.bench.h, benchmarks/benchmark_main.cpp
Add benchmarks for Future, RescheduledLazy and Uthread
=> Add more benchmarks

async_simple/CMakeLists.txt, async_simple/Future.h, async_simple/coro/test/CMakeLists.txt, async_simple/executors/test/CMakeLists.txt, async_simple/executors/test/SimpleIOExecutorTest.cpp, async_simple/test/CMakeLists.txt, async_simple/uthread/Await.h, async_simple/uthread/Latch.h, async_simple/uthread/test/UthreadTest.cpp, async_simple/util/test/CMakeLists.txt, demo_example/CMakeLists.txt
=> Revert "switch-off uthread on not supported platform (#66)"

README.md, README_CN.md, async_simple/CMakeLists.txt, async_simple/Future.h, async_simple/executors/SimpleExecutor.cpp, async_simple/executors/SimpleExecutor.h, async_simple/executors/test/SimpleIOExecutorTest.cpp, async_simple/uthread/Await.h, async_simple/uthread/Latch.h, async_simple/uthread/test/UthreadTest.cpp, async_simple/util/ThreadPool.h, benchmarks/Uthread.bench.cpp
fix simple executor ub issue
fix uthread unittest asan issue
Reopen #66 #70 
Close #69 
Fix SimpleExecutor UB #59 
Add SimpleExecutor.cpp #67
=> make uthread portable

async_simple/executors/SimpleExecutor.cpp, async_simple/executors/test/CMakeLists.txt, async_simple/util/Queue.h, async_simple/util/ThreadPool.h, async_simple/util/test/ThreadPoolTest.cpp, benchmarks/CMakeLists.txt, benchmarks/ThreadPool.bench.cpp, benchmarks/ThreadPool.bench.h
The current thread pool don't support cross platform, refactor it to provide a cross-platform, work-steal thread pool.
=> [Cross Platform]Refactor thread pool

async_simple/coro/test/LazyTest.cpp
=> fix test case

demo_example/CMakeLists.txt, demo_example/asio_util.hpp, demo_example/async_echo_server.cpp, demo_example/http/coroutine_http/http_server.cpp, demo_example/http/coroutine_http/multiple_core_http_server.cpp, demo_example/io_context_pool.hpp
Add a demo show how to write a multiple core http server with async_simple. The performance will be greatly improved by utilizing multiple core.
=> [Demo Example]Add multiple core demo

async_simple/coro/SpinLock.h, async_simple/coro/test/SpinLockTest.cpp
add spin lock implement based on c++20 coroutines
new feature
=> [coro] add spin lock

async_simple/coro/ConditionVariable.h, async_simple/coro/test/ConditionVariableTest.cpp
add condition variable
note: the `TEST_F(ConditionVariableTest, testMultiWait)` can not passed on asan check. need fix it before merge
=> [coro] add condition variable

async_simple/util/ThreadPool.h
=> Avoid unused member warning in ThreadPool

docs/docs.cn/ConditionVariable.md, docs/docs.cn/Lock.md, docs/docs.en/ConditionVariable.md, docs/docs.en/Lock.md
add spin lock, condition variable related documents
=> [docs] add spin lock and condition variable documents

NOTICE, async_simple/coro/Mutex.h, async_simple/coro/test/MutexTest.cpp
Offering asynchronous mutex component.
=> Offering Mutex

async_simple/Executor.h, async_simple/coro/LazyHelper.h
=> cleanup useless executor interface

async_simple/coro/Collect.h, async_simple/coro/Lazy.h, async_simple/coro/test/LazyTest.cpp, docs/docs.cn/Lazy.md, docs/docs.en/Lazy.md
See [pr 130](https://github.com/alibaba/async_simple/pull/130)
=> Add variadic support for collectAny 

async_simple/coro/Sleep.h, async_simple/coro/test/SleepTest.cpp
https://github.com/alibaba/async_simple/issues/133
=> add a sleep function overloading

demo_example/CMakeLists.txt
sub pr of https://github.com/alibaba/async_simple/pull/139
=> fix build fail when as subproject

async_simple/coro/Lazy.h
=> Use std::variant insted of union in LazyPromisew

.github/workflows/conan.yml, README.md, README_CN.md, conanfile.py
Conan is a C/C++ Package Manager.
Support Conan to get more potential users
- add conan recipe `conanfile.py`
- update README
- add conan ci
=> add conan recipe

benchmarks/CMakeLists.txt, benchmarks/CallDepth.bench.cpp, benchmarks/CallDepth.bench.h, benchmarks/PureSwitch.bench.cpp, benchmarks/PureSwitch.bench.h, benchmarks/ReadFile.bench.cpp, benchmarks/ReadFile.bench.h, benchmarks/ReadFileUtil.hpp, benchmarks/benchmark_main.cpp
add benchmark to compare Lazy and Thread
- add call depth benchmark
- add read file benchmark
- add switch benchmark
=> add benchmark: Lazy vs. Uthread

demo_example/ReadFiles.cpp
=> fix(#168): Simplify do_for_each

benchmarks/PureSwitch.bench.cpp, benchmarks/ReadFileUtil.hpp
=> fix: no-uthread bencharks compile fail

README_CN.md
=> Update README about bazel build

.github/workflows/bazel.yml, .github/workflows/windows.yml, benchmarks/ReadFileUtil.hpp
=> Adjust bazel CI for windows

README.md, README_CN.md
=> Update the README about bazel build

CMakeLists.txt
https://github.com/alibaba/async_simple/issues/202
=> Use FetchContent_Declare get gtest

.github/workflows/windows.yml
https://github.com/alibaba/async_simple/issues/143
=> Open compile test for windows ci

async_simple/coro/Traits.h, async_simple/coro/ViaCoroutine.h, async_simple/coro/test/FutureAwaiterTest.cpp, async_simple/coro/test/TraitsTest.cpp
=> Refactor coroutine traits

ChangeLog
Add a changelog file to records the significant changes during the development.
=> Add ChangeLogs

async_simple/util/ThreadPool.h, benchmarks/ThreadPool.bench.cpp, docs/docs.cn/Executor.md, docs/docs.en/Executor.md
Close https://github.com/alibaba/async_simple/issues/209.
=> [Executors] Refactor ThreadPool to make sure all the scheduled task would be executed

README.md, README_CN.md, docker/centos7/Dockerfile
https://github.com/alibaba/async_simple/issues/175
=> Add centos7 Dockerfile

README.md, README_CN.md, docker/ubuntu/Dockerfile
@4kangjc
https://github.com/alibaba/async_simple/issues/175
```
/root/async_simple
-- The CXX compiler identification is Clang 13.0.1
-- The C compiler identification is Clang 13.0.1
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /usr/bin/clang-13
-- Detecting CXX compiler ABI info
....
-- The CXX compiler identification is GNU 11.3.0
-- The C compiler identification is GNU 11.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/gcc-11
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-11 - skipped
```
=> Add ubuntu Dockerfile

async_simple/uthread/Uthread.h, async_simple/uthread/internal/thread.cc, async_simple/uthread/internal/thread.h
=> add uthread attribute stack size

async_simple/Try.h
=> use std::variant instead of union in Try

async_simple/uthread/Await.h, async_simple/uthread/test/UthreadTest.cpp
=> Refactor uthread::await

async_simple/uthread/Await.h, async_simple/uthread/test/UthreadTest.cpp
=> fix: uthread test

async_simple/Future.h, async_simple/test/FutureTest.cpp
还是不应该直接改`value_type`，不然`Futrue<void>`用不了`CollectAll`
=> fix Future<void> CollectAll

async_simple/coro/Lazy.h
Closes https://github.com/alibaba/async_simple/issues/228
=> Remove redundant template parameters

.github/workflows/clang-format.yml, README.md, README_CN.md
After we use more concepts in the project, the format CI often fails and it is confusing. Document the related behavior to avoid the confusion as much as possible.
=> Document the problem with clang-format version

async_simple/coro/Collect.h, async_simple/coro/Lazy.h
Closes https://github.com/alibaba/async_simple/issues/159
=> refactor coro::CollectAll

CMakeLists.txt
https://github.com/alibaba/async_simple/issues/234
=> fix: gcc12 compile fail

.github/workflows/cmake_gcc.yml
https://github.com/alibaba/async_simple/issues/234
=> Adjust CI: add gcc-11 and gcc-12

async_simple/Collect.h, async_simple/uthread/Collect.h
=> Add constraints for Iterator class

async_simple/uthread/Async.h, async_simple/uthread/Uthread.h, async_simple/uthread/test/UthreadTest.cpp, docs/docs.cn/Uthread.md, docs/docs.en/Uthread.md
=> Add the second version of uthread::async

README.md, README_CN.md
Closes #256 
Add document about how to fix msvc C4737.
=> Add document about how to fix msvc C4737

async_simple/coro/Collect.h, async_simple/coro/test/LazyTest.cpp
=> Add `value()` and `index()` interfaces to `CollectAnyResult`

async_simple/Future.h, async_simple/test/FutureTest.cpp, docs/docs.cn/Future.md, docs/docs.en/Future.md
=> feat: add `future::then` interface

docs/docs.cn/GetStarted.md, docs/docs.en/GetStarted.md
…nc_simple/coro/SyncAwait.h"
Closes #264
add head file
```c++
#include "async_simple/coro/SyncAwait.h"
```
=> docs: Add header file

async_simple/Try.h, async_simple/test/TryTest.cpp
=> Adjust the constructor of Try

BUILD.bazel, WORKSPACE.bazel, bazel/config/BUILD.bazel
https://github.com/bazelbuild/bazel/issues/8622
=> Use @platforms instead of @bazel_tools

async_simple/coro/ConditionVariable.h, async_simple/coro/test/ConditionVariableTest.cpp
=> feat: add the interface of `coro::ConditionVariable notifyOne and notifyAll`

async_simple/coro/Latch.h, async_simple/coro/test/LatchTest.cpp, docs/docs.cn/Latch.md, docs/docs.en/Latch.md
https://github.com/alibaba/async_simple/issues/270
=> feat: add `coro::Latch`

async_simple/coro/Semaphore.h, async_simple/coro/test/ConditionVariableTest.cpp, async_simple/coro/test/SemaphoreTest.cpp, docs/docs.cn/ConditionVariable.md, docs/docs.cn/Semaphore.md, docs/docs.en/ConditionVariable.md, docs/docs.en/Semaphore.md
https://github.com/alibaba/async_simple/issues/269
=>  feat: add `coro::Semaphore`

async_simple/Collect.h, async_simple/coro/Lazy.h
Closes https://github.com/alibaba/async_simple/issues/274
=> Fix: do not use logicAssert in noexcept functions

async_simple/coro/Collect.h, async_simple/coro/Lazy.h, async_simple/coro/test/LazyTest.cpp, docs/docs.cn/Lazy.md, docs/docs.en/Lazy.md
https://github.com/alibaba/async_simple/issues/276
https://github.com/alibaba/async_simple/issues/163
=> RescheduleLazy should be only allowed in DetachedCoroutine

async_simple/coro/Collect.h
=> Optimize coro::collectAny(LazyType<Ts>...) implement

README.md, README_CN.md
=> Fix compiler requirements in README

.github/workflows/clang-format.yml, README.md, README_CN.md, async_simple/coro/Latch.h
当格式有问题时，clang-format 会失败，不会 show difference
https://github.com/alibaba/async_simple/actions/runs/3918686370/jobs/6699218025
https://github.com/alibaba/async_simple/actions/runs/3918696512/jobs/6699233687
=> Fix: clang-format failed

async_simple/Executor.h
=> private to protected

.github/workflows/conan.yml, conanfile.py
fix conan ci
- conan 2.0 compat
=> fix conan ci

README.md, README_CN.md
update README
- add website link to README
=> [no ci] update README

async_simple/FutureState.h
=> Change the memory order of `detach` to memory_order_acq_rel

bazel/config/BUILD.bazel
https://github.com/alibaba/async_simple/issues/297
=> Remove bazel config_setting async_simple_enable_tests

docs/docs.en/Lazy.md
=> mistake in writing

async_simple/FutureState.h, async_simple/coro/Lazy.h
Closes https://github.com/alibaba/async_simple/issues/302
=> fix: GCC 13 compilation failed

async_simple/Future.h, async_simple/coro/FutureAwaiter.h, async_simple/coro/ViaCoroutine.h, async_simple/coro/test/FutureAwaiterTest.cpp
=> refactor : optimize FutureAwaiter

async_simple/coro/DetachedCoroutine.h, async_simple/coro/Lazy.h, async_simple/coro/test/LazyLocalTest.cpp, docs/docs.cn/Lazy.md, docs/docs.en/Lazy.md
=> feat: add new feature lazy_local

async_simple/coro/Lazy.h
This patch tries to introduce `get_return_object_on_allocation_failure()` to the promise_type of Lazy.
Why do we want to introduce `get_return_object_on_allocation_failure()`? Since
a coroutine will be roughly converted to:
```C++
void *frame_addr = ::operator new(required size);
__promise_ = new (frame_addr) __promise_type(...);
__return_object_ = __promise_.get_return_object();
co_await __promise_.initial_suspend();
try {
function-body
} catch (...) {
__promise_.unhandled_exception();
}
co_await __promise_.final_suspend();
```
Then we can find that the coroutine should be nounwind (noexcept) naturally if
the constructor of the promise_type, the get_return_object() function, the
initial_suspend, the unhandled_exception(), the final_suspend and the allocation
function is noexcept.
For the …
=> Introduce get_return_object_on_allocation_failure to Lazy (#338)

README.md
Fixes grammar & typo.
README.md
=> docs: fix grammar & typo

async_simple/coro/CountEvent.h
=> refactor: delete useless class forward declaration

README.md, README_CN.md
simply document to helper newcomer install and user async-simple.
=> [doc] add description for install by vcpkg, simply install document

async_simple/CMakeLists.txt
https://github.com/xmake-io/xmake-repo/issues/3569
=> fix missing install headers

.github/workflows/macosx.yml, MODULE.bazel
=> [ci] fix bazel ci

async_simple/coro/test/PMRLazyTest.cpp
=> fix compile error,maybe uninitialized variable

MODULE.bazel
Fix https://github.com/alibaba/async_simple/issues/417
=> fix(bazel): update boring_ssl version
