alibaba/async_simple

async_simple/experimental/coroutine.h

The current implementation for coroutine.h would be problematic if we
use the combination of clang and libstdc++ (version > 10). Provide
solution for it.

Provide compatible coroutine.h between compiler and std library

---

async_simple/experimental/coroutine.h

Make async_simple if <version> is not presented.

Include <version> conditionally

---

async_simple/Executor.h
async_simple/coro/LazyHelper.h
async_simple/coro/Task.h
async_simple/util/Condition.h

We'd better avoid use specific os api to implement a Condition, we can use std::condition_variable to implement this to support cross platform.
Actually c++20 has already provided [semaphore](https://en.cppreference.com/w/cpp/thread/counting_semaphore) , but clang has not supported it yet, however we could keep the same api with c++20 semaphore, so the implementation of Condition.h and API changes. We can remove Condition in future when the compilers are ready for semaphore.
for #33 
Remove futes dependency, change the APIs according to c++20 [semaphore](https://en.cppreference.com/w/cpp/thread/counting_semaphore).

[Cross platform]use std::condition_variable

---

async_simple/coro/Collect.h
async_simple/experimental/coroutine.h

The previous implementation of `coroutine.h" is based on coroutine TS. And it is slightly different from C++20 <coroutine>.  This patch makes the implementation of "coroutine.h" conforming with C++20 <coroutine>.
This would solve issue https://github.com/alibaba/async_simple/issues/41 too.

Conform C++20 <coroutine>

---

.github/workflows/Performance.yml

We need monitoring every commit and PR to avoid unimagined regressions.
We would receive an comment if the PR or commit cause a regression greater than 50%.
https://github.com/ChuanqiXu9/async_simple/pull/5#commitcomment-68189590

Enable Performance CI

---

.github/workflows/PerformanceCommit.yml
.github/workflows/PerformancePR.yml
.gitignore

Due to the access control system, we need different actions for PR and commit. For example, we need record the performance of every commit. But we shouldn't record for every PR.

Split Performance CI

---

async_simple/CMakeLists.txt
async_simple/Future.h
async_simple/coro/test/CMakeLists.txt
async_simple/executors/test/CMakeLists.txt
async_simple/executors/test/SimpleIOExecutorTest.cpp
async_simple/test/CMakeLists.txt
async_simple/uthread/Await.h
async_simple/uthread/Latch.h
async_simple/uthread/test/UthreadTest.cpp
async_simple/util/test/CMakeLists.txt
demo_example/CMakeLists.txt

1. disable uthread on not supported platform
2. fix SimpleIOExecutorTest failed without libaio
3. no need to link async_simple when uthread disabled, because there is no other cpp source file
Close #39

switch-off uthread on not supported platform

---

benchmarks/Lazy.bench.cpp

I compiled async_simple with gcc11, an compile error shows:
```
async_simple/benchmarks/Lazy.bench.cpp:23:58:   recursively required from ‘LazyType<int> lazy_fn<LazyType, N>::operator()() [with LazyType = async_simple::coro::Lazy; int N = 948]’
async_simple/benchmarks/Lazy.bench.cpp:23:58:   required from ‘LazyType<int> lazy_fn<LazyType, N>::operator()() [with LazyType = async_simple::coro::Lazy; int N = 949]’
async_simple/benchmarks/Lazy.bench.cpp:53:68:   required from here
async_simple/async_simple/coro/Lazy.h:130:15: fatal error: template instantiation depth exceeds maximum of 900 (use ‘-ftemplate-depth=’ to increase the maximum)
130 |               typename = std::enable_if_t<std::is_convertible_v<V&&, T>>>
|               ^~~~~~~~
compilation terminated.
```
This PR solves the …

[Compile Error]fix an error for gcc11

---

async_simple/coro/Lazy.h
async_simple/coro/test/LazyTest.cpp
demo_example/async_echo_server.cpp
demo_example/http/coroutine_http/http_server.cpp

simplify code:
```via(&executor).start([](auto&&) {});```
to
```via(&executor).detach();```

[Simplify Interface]add detach

---

CMakeLists.txt
async_simple/CMakeLists.txt

current ci not run uthread benchmark
move uthread detect to top cmake file to make sure UTHREAD variable can be used in benchmark directory

fix benchmark uthread detect

---

async_simple/Executor.h
async_simple/coro/CoAwait.h
async_simple/coro/Collect.h
async_simple/coro/Event.h
async_simple/coro/Lazy.h
async_simple/coro/Util.h
async_simple/coro/test/LazyTest.cpp
async_simple/coro/test/ViaCoroutineTest.cpp
async_simple/experimental/coroutine.h
async_simple/uthread/test/UthreadTest.cpp
demo_example/asio_util.hpp

We could use coroutine components under std directly by using
experimental ones in std namespace. So the code would be cleaner.

Enable to use coroutine components under std directly

---

CMakeLists.txt
async_simple/CMakeLists.txt
async_simple/Common.h
async_simple/FutureState.h
async_simple/LocalState.h
async_simple/Try.h
async_simple/coro/Collect.h
async_simple/coro/Lazy.h
async_simple/coro/test/LazyTest.cpp
async_simple/executors/SimpleIOExecutor.h
async_simple/executors/test/CMakeLists.txt
async_simple/experimental/coroutine.h
async_simple/test/FutureTest.cpp
async_simple/uthread/Async.h
async_simple/uthread/internal/thread.cc
demo_example/CMakeLists.txt
demo_example/io_context_pool.hpp
demo_example/smtp/smtp_client.cpp

Closes #72 
name conflicts to windows:
- _try --> _try_value
- Yield() --> Yield_t()
not exist functions on windows:
- ```__builtin_expect --> #define __builtin_expect(EXP, C) (EXP)```
- ```__attribute__((__always_inline__)) --> #define FL_INLINE inline```
change some compile options for windows:
- pthread
- async_simple static lib
- some c++ compile options

Support windows

---

async_simple/coro/CoAwait.h
async_simple/coro/Lazy.h
async_simple/coro/Util.h
dbg/LazyStack.py
docs/docs.cn/调试 Lazy.md
docs/docs.en/DebuggingLazy.md

- Offering gdb scripts to print the asynchronous stack trace for stackless coroutine components in async_simple.
- Add document for debugging stalkless coroutine and how to use the new script.

Support dbg scripts and document for debugging

---

async_simple/experimental/coroutine.h

If we chose standard implementation for coroutine, the current implementation might met a redefinition error for std::hash<std::coroutine> type.

Don't set std::hash<coroutine> in case we use std implementation

---

async_simple/uthread/test/UthreadTest.cpp

Newest clang would check if the captured variables are used or not. So it would block async_simple to be compiled by newest clang.

Remove unused captures

---

async_simple/coro/test/LazyTest.cpp
async_simple/test/unittest.h

The using statement in unittest.h is meaningless and it is possible to
make async_simple incompatible for user whose version of goolgetest is
not high enough.

Remove unused using in unittest.h

---

async_simple/coro/test/LazyTest.cpp

Closing #92 
The reason here should be the lackness of the optimization of GCC for coroutines.

Decrease the scale in testLazyPerf to make GCC compatible

---

async_simple/util/ThreadPool.h

Given we are already in linux system, we could call syscall directly.

Don't include <pthread> in ThreadPool.h

---

async_simple/coro/Lazy.h
async_simple/coro/LazyHelper.h
async_simple/coro/test/LazyTest.cpp
demo_example/ReadFiles.cpp

It would be more straight forward to add an executor argument to
syncAwait.
Closing #101

Add executor argument to syncAwait

---

async_simple/Common.h

The previous method to  detect the presence of [[likely]] doesn't think of GCC.  Try to detect it properly.

Detect the presence of [[likely]] properly

---

async_simple/coro/Collect.h
async_simple/coro/test/LazyTest.cpp

Almostly Fix #127
In the variadic overload of collectAll, we can just copy the lazy<T> instead of reference. The copy is trivally.
However, it's expensive to copy in the vector<lazy<T>> overloaded. Maybe we can use span<lazy<T>> to instead, but it will cause interface change.
Luckily, only the empty temporary vector will cause crash(the non empty temporary vector will cause a compiler error in initialization)
see test in LazyTest.cpp

allow temporary object as param in variadic collectAll

---

async_simple/Executor.h
async_simple/coro/ViaCoroutine.h

```
In file included from /home/fantasy/.xmake/packages/a/async_simple/main/4e0143c97b65425b855ad5fd03038b6a/include/async_simple/coro/ViaCoroutine.h:29,
from /home/fantasy/.xmake/packages/a/async_simple/main/4e0143c97b65425b855ad5fd03038b6a/include/async_simple/coro/Lazy.h:22,
from /home/fantasy/wormhole/include/utils.h:9,
from /home/fantasy/wormhole/src/wormhole_client.cpp:11:
/home/fantasy/.xmake/packages/a/async_simple/main/4e0143c97b65425b855ad5fd03038b6a/include/async_simple/Executor.h: In member function ‘virtual bool async_simple::Executor::checkin(async_simple::Executor::Func, async_simple::Executor::Context, async_simple::ScheduleOptions)’:
/home/fantasy/.xmake/packages/a/async_simple/main/4e0143c97b65425b855ad5fd03038b6a/include/async_simple/Executor.h:102:45: warning: unused …
```

fix unused parameter warning

---

async_simple/Common.h
async_simple/Try.h
async_simple/coro/Collect.h
async_simple/coro/Lazy.h
async_simple/uthread/Async.h
async_simple/uthread/internal/thread.cc

rename LIKELY/UNLIKELY to avoid definition conflict (#135)

---

async_simple/coro/SyncAwait.h

```c++
#include <async_simple/coro/SyncAwait.h>
```
compile fail
```
In file included from /Users/shuoshu/code/coro_rpc/demo.cpp:4:
async_simple/coro/SyncAwait.h:40:5: error: no template named 'Try'
Try<ValueType> value;
^
async_simple/coro/SyncAwait.h:42:32: error: no template named 'Try'
.start([&cond, &value](Try<ValueType> result) {
^
async_simple/coro/SyncAwait.h:52:40: error: unknown type name 'Executor'
inline auto syncAwait(LazyType &&lazy, Executor *ex) {
^
3 errors generated.
ninja: build stopped: subcommand failed.
```

fix missing headers

---

async_simple/uthread/Await.h

`std::result_of` deprecated in C++17 and removed in C++20
see https://en.cppreference.com/w/cpp/types/result_of
replace `std:: result_of` by `std::invoke_result`

fix: build fail with libc++

---

async_simple/coro/Lazy.h
async_simple/coro/test/LazyTest.cpp

Closes #154 
`Lazy` and `RescheduleLazy` migrate to `LazyBase`.

GH-154: Lazy & RescheduleLazy migrate to LazyBase

---

benchmarks/ReadFile.bench.cpp

修改了ReadFile.bench.cpp下无符号整数与有符号整数比较产生的编译错误

fix: sign compare on gcc compile fail

---

async_simple/uthread/Async.h
async_simple/uthread/Collect.h

https://github.com/alibaba/async_simple/issues/171
重构`uthread::Launch`，修改为`enum class`
https://github.com/alibaba/async_simple/issues/171

Refactor launch

---

benchmarks/CallDepth.bench.cpp
benchmarks/ReadFile.bench.cpp
benchmarks/ReadFileUtil.hpp
benchmarks/benchmark_main.cpp

Fix benchmark compile fail on other platform

---

CMakeLists.txt
async_simple/Future.h
async_simple/Try.h
async_simple/coro/FutureAwaiter.h
async_simple/coro/Lazy.h
async_simple/coro/Traits.h
async_simple/coro/ViaCoroutine.h
async_simple/uthread/Async.h
async_simple/uthread/Collect.h

The compiler output of `std::enable_if` is really ugly, and as proposed in #172, it's better to replace the old SFINAE utility function with the new C++20 `concept`.
Closes #172.
I've tried my best to replace every occurrence of `std::enable_if` in the async_simple folder. I've also merged some of the functions by `if constexpr` instead of splitting the function definitions.
(Also, don't blame me for the code style I committed, because this is not what I typically use. It was adjusted as per the clang format output in one of the Workflows, or otherwise, I can't even pass the CI tests.)

Replace all std::enable_if by C++20 concept

---

.github/workflows/macosx.yml

bazel 在windows上可能还会改改，先弄一下macos的
macos虽然是unix系统，但鉴于`uthread`还不支持macos,增加个CI吧

Adjust CI for MacOS

---

benchmarks/ThreadPool.bench.cpp

ThreadPoll并不会在其生命周期结束时执行完所有的任务，所以`assert`为false的可能性很大，由于`build type`为`release`时，`assert`断言触发，CI没有检测出来

fix: ThreadPoll benchmark assert false

---

async_simple/Future.h

单独`#include "async_simple/Future.h"`时，编译会报错
`Future.h`里`include`了`Promise.h`，`Promise.h`里又`include`了`Future.h`，导致单独编译`Futrue.h`时，找不到`Promise`声明而报错

add Promise forward declaration

---

async_simple/coro/test/LazyTest.cpp

Closes #199
Add getValueWithCV, with will blocked on cv.wait() until be notified, so we can ensure which work will finished first.
Then we can use condition varibale to wait the other unfinished job after CollectAny return instead of sleep a long time, which make test faster and stabler.

Improve testCollectAny/testCollectAnyVariadic

---

async_simple/coro/FutureAwaiter.h
async_simple/coro/test/FutureAwaiterTest.cpp
docs/docs.cn/Future.md
docs/docs.en/Future.md

```.cpp
Promise<int> pr;
auto fut = pr.getFuture();
sum(1, 1, [pr = std::move(pr)](int val) mutable { pr.setValue(val); });
auto val = co_await fut;
auto original = fut.value(); // access future again
EXPECT_EQ(val, original);
```
```.cpp
Promise<int> pr;
auto fut = pr.getFuture();
sum(1, 1, [pr = std::move(pr)](int val) mutable { pr.setValue(val); });
auto val = co_await std::move(fut);
auto original = fut.value(); // don't access future due to the object has moved
```
Enable access future after `co_await future`.

Operator co_await should force to move future

---

async_simple/Future.h
async_simple/Promise.h
async_simple/Traits.h
async_simple/Try.h
async_simple/test/FutureTest.cpp
async_simple/uthread/Collect.h
demo_example/ReadFiles.cpp

Allow `futrue<void>` and `promise<void>`
```cpp
TEST_F(FutureTest, testVoidFuture) {
Promise<void> p;
auto f = p.getFuture();
int i = 0;
EXPECT_FALSE(f.hasResult());
f.setContinuation([&i](Try<void>) { EXPECT_EQ(i, 5); });
i = 5;
p.setValue();
EXPECT_TRUE(f.hasResult());
Promise<void> p2;
auto f2 = p2.getFuture()
.thenTry([](Try<void>) {
})
.thenTry([](Try<void> t) { return t.value(); })
.thenValue([]() { return 10; })
.thenValue([](int i) { EXPECT_EQ(i, 10); });
p2.setValue();
f2.wait();
}
```

allow future<void> and promise<void>

---

async_simple/CMakeLists.txt
async_simple/Common.h
async_simple/uthread/internal/thread.cc
async_simple/uthread/internal/thread_impl.h
async_simple/uthread/test/CMakeLists.txt

Closes https://github.com/alibaba/async_simple/issues/178

Implementing start_switch_fiber and finish_switch_fiber for uthread to enable address sanitizer

---

async_simple/coro/Collect.h

我的疏忽，目前`Deducing This`这个特性在gcc和clang上还没实现，所以编译选项改成`-std=c++23`会编译错误

Fix: Deducing This is not yet implemented in gcc and clang

---

CMakeLists.txt
async_simple/coro/Generator.h
async_simple/coro/PromiseAllocator.h
async_simple/coro/test/GeneratorTest.cpp
bazel/config/copt.bzl

https://github.com/alibaba/async_simple/issues/103
TODO:
add documents

feat: Add Generator

---

demo_example/CMakeLists.txt

The CI on MacOS may fail due to the deprecated declarations in the demo.  We can set `-Wno-xx`  option simply since it is a demo.

Set -Wno-deprecated-declarations for demo_examples in MacOS

---

.github/workflows/cmake.yml
.github/workflows/cmake_gcc.yml
.github/workflows/macosx.yml

Some Ci scripts forget to add `-j` option to speed up building.

Make Some CI compile simultaneously

---

CMakeLists.txt
async_simple/FutureState.h

Closes https://github.com/alibaba/async_simple/issues/234
之前的做法只针对cmake生效, bazel等其他编译工具无法生效

fix: GCC 12 issues a spurious uninitialized-var warning

---

async_simple/Future.h
async_simple/test/FutureTest.cpp

在demo_example/ReadFiles.cpp这个例子中有bug，下面是原来的运行结果，可以看到，future例子没有输出
```bash
Calculating char counts synchronously.
Files contain 1586 'x' chars.
Calculating char counts asynchronously by future.
Calculating char counts asynchronously by coroutine.
Files contain 1586 'x' chars.
```
下面是更改之后的输出，我认为问题出在 makeReadyFuture 中，创建一个makeReadyFuture应该是可以通过新增加TEST断言。
```bash
Calculating char counts synchronously.
Files contain 1586 'x' chars.
Calculating char counts asynchronously by future.
Files contain 1586 'x' chars.
Calculating char counts asynchronously by coroutine.
Files contain 1586 'x' chars.
```
```c++
inline Future<void> makeReadyFuture() {
return Future<void>(Try<Unit>(Unit()));
}
```

fix: makeReadyFuture

---

async_simple/Executor.h
async_simple/coro/Lazy.h

Remove some unnecessary lambda wrap as std::coroutine_handle<> is callable object

refactor: remove unnecessary lambda wrap

---

async_simple/coro/Dispatch.h
async_simple/coro/test/DispatchTest.cpp
docs/docs.cn/dispatch.md
docs/docs.en/dispatch.md

支持通过 `co_await dispatch(executor) `将本协程调度到对应的executor上执行
- `LazyPromiseBase `加了一个数据成员 `_caller_detached_coroutine`，用来标识caller协程是否为DetachedCoroutine。`_continuation`被类型擦除了，而我们需要运行时更新caller协程的executor，因此需要一个flag区分不同的promise类型并执行运行时转换。
- 新增一个接口函数：` DispatchAwaitable dispatch(Executor* ex)`
```c++
TEST(DispatchTest, testDispatch) {
async_simple::executors::SimpleExecutor executor1(2);
async_simple::executors::SimpleExecutor executor2(2);
auto task = [&]() -> Lazy<> {
Executor* ex = co_await CurrentExecutor{};
EXPECT_EQ(ex, &executor1);
co_await dispatch(&executor1);
EXPECT_EQ(ex, &executor1);
co_await dispatch(&executor2);
ex = co_await CurrentExecutor{};
EXPECT_EQ(ex, &executor2);
};
async_simple::coro::syncAwait(task().via(&executor1));
}
```

add dispatch (#314)

---

async_simple/coro/Lazy.h

The CI shows that GCC doesn't know about `std::max_align_t`. This should be a GCC's bug. Use `::max_align_t` to workaround this.

Fix GCC build failures

---

async_simple/coro/ViaCoroutine.h

因为Future的coAwait函数返回的是Awaitable对象，因此需要修改detail::coAwait函数使其确定性的返回Awaiter对象，在抽象层上保证语义不变。
（如果要Future的coAwait函数返回Awaiter对象，那么Future.h和FutureAwaiter.h就是相互包含的，比较难搞）

fix: ensure coAwait returns awaiter object; add include cassert

---

async_simple/coro/SharedMutex.h

优化SharedMutex的实现，在没有达到临界条件下不需要`co_await cv.wait()`

refactor: optimize SharedMutex

---

benchmarks/PureSwitch.bench.cpp

The const-ref version of this method can permit undesired compiler optimizations in benchmarks

fix: benchmark::DoNotOptimize(const Tp&) is deprecated

---

async_simple/coro/Lazy.h

This patch tries to introduce `get_return_object_on_allocation_failure()` to the promise_type of Lazy.
Why do we want to introduce `get_return_object_on_allocation_failure()`? Since
a coroutine will be roughly converted to:
```C++
void *frame_addr = ::operator new(required size);
__promise_ = new (frame_addr) __promise_type(...);
__return_object_ = __promise_.get_return_object();
co_await __promise_.initial_suspend();
try {
function-body
} catch (...) {
__promise_.unhandled_exception();
}
co_await __promise_.final_suspend();
```
Then we can find that the coroutine should be nounwind (noexcept) naturally if
the constructor of the promise_type, the get_return_object() function, the
initial_suspend, the unhandled_exception(), the final_suspend and the allocation
function is noexcept.
For the …

Introduce get_return_object_on_allocation_failure to Lazy

---

.github/workflows/cmake.yml

While we don't run benchmarks now, it is still worth to compile the benchmarks in CI.

Compile benchmarks in CI

---

async_simple/Try.h

async-simple Try.h中存在报错信息拼写错误
old："Try object do not has on error"
fixed: "Try object do not has an error"
#343

fix error message for Try.h

---

bazel/config/copt.bzl

```
ASYNC_SIMPLE_COPTS = select({
"@com_github_async_simple//bazel/config:msvc_compiler": [
"/std:c++20",
"/await:strict",
"/EHa"
],
"//conditions:default": [
"-std=c++20",
"-D_GLIBCXX_USE_CXX11_ABI=1",
"-Wno-deprecated-register",
"-Wno-mismatched-new-delete",
"-fPIC",
"-Wall",
"-Werror",
"-D__STDC_LIMIT_MACROS",
"-g",
],
})
```
假设一项目依赖async_simple:
```
package(default_visibility = ["//visibility:public"])
load("@com_github_async_simple//bazel/config:copt.bzl", "ASYNC_SIMPLE_COPTS")
cc_test(
name = "test",
srcs = glob(["test/*.cc", "test/*.h"]),
includes = ["test"],
copts = ASYNC_SIMPLE_COPTS,
deps = [
"@googletest//:gtest",
"@googletest//:gtest_main",
"@com_github_async_simple//:async_simple",
]
)
```
如果不在`ASYNC_SIMPLE_COPTS`的定义里显式指定Repository的话构建会失败：
ERROR: Analysis of target '//:test' …

build: fix bazel build bug

---

CMakeLists.txt
async_simple/Executor.h
async_simple/MoveWrapper.h
async_simple/executors/test/SimpleExecutorTest.cpp
bazel/config/copt.bzl
docs/docs.cn/Executor.md
docs/docs.en/Executor.md

feat: restore MoveWrapper to maintain forward compatibility; add schedule_move_only interface

feat: restore MoveWrapper to maintain forward compatibility; add schedule_move_only interface

---

async_simple/coro/ResumeBySchedule.h
async_simple/coro/test/ResumeByScheduleTest.cpp
docs/docs.cn/Future.md
docs/docs.en/Future.md

`co_await future` resume的时候是走schedule还是checkin，应该由用户来决定，现在的实现默认走checkin，很多情况下是没必要的。
注：不应该通过不实现Executor的checkin接口来达到上述目的，因为很可能一些Future需要checkin而一些Future不需要。
no incompatible changes

feat: add Future.setResumeBySchedule interface

---

async_simple/coro/test/CMakeLists.txt

The current CMake settings do not specifically address AppleClang 15.x versions, which is needed to handle certain compiler errors.
macos 14.2.1 (m2) version of clang:
```
message("Compiler ID: ${CMAKE_CXX_COMPILER_ID}")
message("Compiler Version: ${CMAKE_CXX_COMPILER_VERSION}") 
```
Added a condition in CMakeLists.txt to apply the -Wno-unsequenced option specifically for AppleClang 15.x

fix: update CMakeLists for AppleClang 15.x Support

---

CMakeLists.txt
async_simple/coro/Collect.h
async_simple/coro/test/GeneratorTest.cpp

fix compile error on gcc10.2 or lower version;
fix compile error on msvc;
add no-unused-value when gcc10.2 or lower;
use (std::min) instead of std::min to avoid conflict on windows;

[fix] fix compile

---

.github/workflows/conan.yml

upgrade conan ci system version to ubuntu 22.04 and clang version to clang17.

upgrade clang version to clang17 for conan

---

async_simple/coro/test/CMakeLists.txt

add compile option for msvc to avoid compile error when add more test code:
https://github.com/alibaba/async_simple/actions/runs/8200305183/job/22426819820#step:4:304

add compile option for msvc

---

.github/workflows/cmake_gcc.yml
async_simple/coro/Collect.h
async_simple/coro/test/LazyTest.cpp

fix the bug that collectAny can not accept move_only functor as callback

---

.gitignore
MODULE.bazel

fix warning, see also https://github.com/bazelbuild/bazel/issues/18958

chore(bazel): support bzlmod

---

async_simple/coro/Generator.h

before this change, the build fails, because `AlloAllocator` is not defined when the standard library provides `std::generator`, and the tree is built with C++23.
in this change, we replace `AlloAllocator` with `Allocator`. and the tree builds fine.
also, we include `<generator>` only if `__cpp_lib_generator` is defined. as the existence of the header does not imply that we are building with C++23.

coro/Generator: correct Generator alias of std::generator 

---

.gitignore
async_simple/coro/Collect.h
async_simple/coro/test/LazyTest.cpp

it seems that After #277 , collectAllPara dont use `SimpleCollectAllVariadicAwaiter`, which is faster by provide `coAwait` method
Fix code that collectAllPara will call `SimpleCollectAllVariadicAwaiter`.

Fix collectAllPara dont use SimpleCollectAllVariadicAwaiter

---

async_simple/coro/Lazy.h
async_simple/coro/test/LazyTest.cpp
async_simple/uthread/Await.h
docs/docs.cn/Executor.md
docs/docs.cn/Lazy.md
docs/docs.en/Executor.md
docs/docs.en/Lazy.md

deprecated `Lazy::setEx()` instead by Lazy::start(cb,ex), which is may not expected behavior.
1. deprecated `Lazy::setEx()`
2. add `Lazy::start(cb,ex)`, which will start a coroutine and binding it to a new executor without scheduling immediately.

Deprecated setEx, instead by start(cb, ex)

---

async_simple/coro/Lazy.h
async_simple/coro/LazyLocalBase.h
async_simple/coro/test/LazyLocalTest.cpp
docs/docs.cn/Lazy.md
docs/docs.en/Lazy.md

Now, the lazy local is a void*, which is dangerous, and user need manage life-time manually.
Refact lazy local. Now we allow user add local variable derived from `LazyLocalBaseImpl`. we aslo support `SimpleLazyLocal` for simple local variable case.
```cpp
struct mylocal : public LazyLocalBaseImpl<mylocal> {
mylocal(std::string name) : _name(std::move(name)) {}
std::string& name() { return _name; }
std::string _name;
};
Lazy<void> task() {
// if no local or local type is not corret, return nullptr
mylocal* local =co_await CurrentLazyLocals<mylocal>{};
assert(base->name()=="Hello");
local->name()="HI";
// if no local variable, return nullptr
LazyLocalBase* local =co_await CurrentLazyLocals{};
assert(local->empty()==false);
}
// local-variable will life until callback finished. User dont …
```

[breakchange] refact lazy local variable

---

async_simple/Signal.h
async_simple/coro/Collect.h

The prev pull requests #402 may cause heap-use-after-free due to some error operation in collectAny
Fix bug by move variable into await_suspend() function's stack local variable

fix collect heap-use-after-free

---

async_simple/coro/Mutex.h
async_simple/coro/SpinLock.h
async_simple/coro/test/SleepTest.cpp

1. Close #391 
2. We found some mistake use of spinlock in [user issue](https://github.com/alibaba/yalantinglibs/issues/881)
1. add cassert header for `Mutex.h`
3. add nodiscard attribute for `SpinLock::coScopedLock()`
4. add assert for `SpinLock::unlock()`

add assert and [[nodiscard]] for spinlock

---

async_simple/Signal.h
async_simple/coro/Collect.h
async_simple/coro/CountEvent.h

When we call `slot::emplace()`, we check signal state before construct handler. however, when `signal::emit()` called, it will set signal state then set the construct handler.
A possible order:
1. Thread A: `slot::emplace()` check signal state, no triggered now.
2. Thread A: `slot::emplace()` construct signal handler.
3. Thread B: `signal::emit()` set signal state
4. Thread B: `signal::emit()` load signal handler and found it's `nullptr`, emit over
5. Thread A `slot::emplace()` set the signal handler by CAS successful. return true.
Now, `slot::emplace()` will return true and signal handler won't be executed. the signal is loss.
`collectAny` should emit signal when the first handler resume, but now it may won't emit it if `downCount` was called in `await_suspend`
`slot::emplace()` will …

fix signal dont triggered bug in collectAll & slot::emplace()

---

async_simple/Signal.h
async_simple/coro/Collect.h
async_simple/coro/test/LazyTest.cpp
async_simple/coro/test/SleepTest.cpp
async_simple/coro/test/SpinLockTest.cpp
async_simple/test/CancellationTest.cpp
docs/docs.cn/信号与任务的取消.md
docs/docs.en/SignalAndCancellation.md

rename emit to emits

---

async_simple/coro/FutureAwaiter.h
async_simple/coro/test/FutureAwaiterTest.cpp

futureAwaiter cancellation test failed in aarch64, it may caused by weak memory order in aarch64.
Add atomic_thread_fence to avoid unexpected memory order, re-enable futureAwaiter cancellation test.

fix futureAwaiter test failed in aarch64
